version: "3.9"

services:
  postgres:
    container_name: postgres
    image: "postgres:14.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
    networks:
      - local
    volumes:
      - .:/app
    working_dir: /app

  homebrew-write:
    container_name: homebrew-write
    image: homebrew-py:0.0.1
    command: "python -u db.py"
    environment:
      DATA_PATH: $DATA_PATH
      TABLE_NAME: $TABLE_NAME
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    networks:
      - local
    volumes:
      - .:/app
    working_dir: /app

  homebrew-api:
    container_name: homebrew-api
    image: "golang:1.16"
    ports:
      - "8080:8080"
    networks:
      - local
    build:
      context: .
      dockerfile: go.dockerfile
    depends_on:
      postgres:
        condition: service_started
    environment:
      PATREON_CLIENT_ID: $PATREON_CLIENT_ID
      PATREON_CLIENT_SECRET: $PATREON_CLIENT_SECRET
      DB_URL: $DB_URL

networks:
  local:
